// src/core/actions/actionTypes.js

const ACTIONS = {
  GENERATE_TASKS: 'GENERATE_TASKS',
  SHOW_TASKS: 'SHOW_TASKS',
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_TASKS: 'DELETE_TASKS',
  UPDATE_GOALS: 'UPDATE_GOALS',
  UPDATE_TASK: 'UPDATE_TASK',
  SHOW_GOAL: 'SHOW_GOAL',
  SHOW_PROGRESS: 'SHOW_PROGRESS',
  DISCUSS_GOAL: 'DISCUSS_GOAL',
  GENERAL_CHAT: 'GENERAL_CHAT',
  COMPLETE_TASK: 'COMPLETE_TASK',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  GET_PROGRESS: 'GET_PROGRESS',
  GET_STATS: 'GET_STATS',
  HELP: 'HELP',
  UNKNOWN: 'UNKNOWN'
};

module.exports = ACTIONS;